### ISSUE TITLE
Instructions for Brew Mac OS method not working on 10.12.2

### ISSUE THREAD

**Issue by doppioslash** [vfxpro99/usd-build-club#12]
I'm using the brew version of the installer on Mac OS Sierra, 10.12.2.

The problem is that PyOpenGL is detected as installed on the system python, and thus not installed to the brew-installed python.
But then it's found missing when the script builds USD with the brew-installed python.

The problem is solved by running the setvars script, and then re-running the installer. 
Or by running the setvars script before installing, in the first place.

After successfully compiling, `usdview` and others fail when running:

```
$ usdview
Traceback (most recent call last):
  File "/usr/local/bin/usdview", line 25, in <module>
    import pxr.Usdviewq as Usdviewq
ImportError: No module named pxr.Usdviewq
```

It would be helpful to add to the instructions to export PYTHONPATH (as found in the [USD FAQs](http://graphics.pixar.com/usd/docs/USD-Frequently-Asked-Questions.html)).
PYTHONPATH needs to be path that this script installs to, which in my case is `/usr/local/`:

This works for me:

```
export USD_INSTALL_ROOT=/usr/local
export PYTHONPATH=$PYTHONPATH:USD_INSTALLROOT/lib/python
```

But then when trying to run `usdview /usr/local/share/usd/tutorials/helloWorld/helloWorld.py` this happens:

```
$ usdview /usr/local/share/usd/tutorials/helloWorld/helloWorld.py
Traceback (most recent call last):
  File "/usr/local/bin/usdview", line 28, in <module>
    Usdviewq.Launcher().Run()
  File "/usr/local/lib/python/pxr/Usdviewq/__init__.py", line 56, in Run
    self.__LaunchProcess(arg_parse_result)
  File "/usr/local/lib/python/pxr/Usdviewq/__init__.py", line 150, in __LaunchProcess
    from mainWindow import MainWindow
  File "/usr/local/lib/python/pxr/Usdviewq/mainWindow.py", line 25, in <module>
    import stageView
  File "/usr/local/lib/python/pxr/Usdviewq/stageView.py", line 36, in <module>
    from pxr import Glf
  File "/usr/local/lib/python/pxr/Glf/__init__.py", line 29, in <module>
    import _glf
ImportError: dlopen(/usr/local/lib/python/pxr/Glf/_glf.so, 2): Symbol not found: __ZNK5boost16re_detail_10620031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /Users/doppioslash/Code/USD/usd-stage-brew/homebrew/opt/openimageio/lib/libOpenImageIO.1.7.dylib
  Expected in: /Users/doppioslash/Code/USD/usd-stage-brew/homebrew/opt/boost/lib/libboost_regex-mt.dylib
 in /Users/doppioslash/Code/USD/usd-stage-brew/homebrew/opt/openimageio/lib/libOpenImageIO.1.7.dylib
```

**Comment by vfxpro99** [comment]
Ugh, I ran into this as well. The problem came down to OIIO linking to a boost in homebrew/opt, but glf compiling against headers found in /usr/local/include/boost.

I had a fix, more fully qualifying the boost resolution for cmake, but I seem to have lost it.

**Comment by enzyme69** [comment]
I also got this issue and wondering how to fix this .... path issue, no solution?

**Comment by meshula** [comment]
According to this message - https://groups.google.com/d/msg/usd-interest/3OdJJvHjc0k/bzn_1qHICAAJ - the instructions are currently working. If there is still an issue, please reopen an issue.
