### ISSUE TITLE
Blender plugin

### ISSUE THREAD

**Issue by bsavery** [vfxpro99/usd-build-club#13]
I noticed a few references to this in the repo.  Is this something you're working on?  How can we combine efforts 

Brian
(RenderMan for Blender plugin maintainer)

**Comment by vfxpro99** [comment]
Hi Brian, it's a long path! I did start having a look at it. Blender uses Python3, USD Python2.7. For the most part the port is trivial, but there are some tricky stumbling blocks. If it's possible to make headway on this, it would be awesome.

**Comment by bsavery** [comment]
Well I haven't looked at the python2 -> python3 conversion yet.  If you
want to stay in python the exporting of scenegraph to USD should be pretty
easy though!

Does the commit
https://github.com/vfxpro99/usd-build-club/commit/061477e5dfaec2cdaade16fea41c88a89b4d9608
build the python3 binding successfully?  If so I might use it to start
looking at a blender plugin...

**Comment by vfxpro99** [comment]
There are tweaks necessary to the USD codebase itself. @c64kernal has got more info.

**Comment by bsavery** [comment]
Yeah I've hacked through some of them. But got stuck on boost Python

**Comment by vfxpro99** [comment]
Present for you. Pull now; it's a work in progress but should help advance your experiments.

**Comment by bsavery** [comment]
Ok thanks!  I'll take a look soon.

**Comment by jdknox** [comment]
Is the main idea to port all the USD python code to python 3 and then rebuild USD using work-in-progress script?

**Comment by enzyme69** [comment]
What is the latest update on USD and perhaps USDZ for Blender with Python 3?

**Comment by enzyme69** [comment]
@bsavery If I am interested with USDZ format (AR, etc), and like to learn more about USD, but I am using Blender, am I stuck --- knowing that there is no Add-On for Blender because it is Python 3 and USD is Python 2.7? I do started to understand USDA to be able to quickly generate varying objects. But not sure what to do with USD itself because no add-on for Blender. I do able to generate USDZ with varying materials and interchange mesh from different OBJ.

**Comment by jdknox** [comment]
I finally got the dependencies working as well as being able to compile against Blender 2.79's `python3.5`.  Now I'm going to see how hard it is to "tweak" the USD code to work with python3.

Does anyone know what is meant by " @c64kernal has got more info." from one of the above [comments](https://github.com/vfxpro99/usd-build-club/issues/13#issuecomment-277025301)?  i.e., where is this info?

**Comment by bsavery** [comment]
Hi @jdknox I did a little work trying to do this.  And would like to combine efforts with someone as I don't have a ton of time.

First of all you have to make sure your boost-python supports python 3.5/6 as the python bindings of USD work off that.  Then there are some tweaks as the python C extensions have changed.  For example you need to change PyString_as_String to either PyUnicode_as_String or PyBytes_as_String.  I was able to work through those, but haven't gotten over the issue of the PyModuleDef changing for Python3

**Comment by c64kernal** [comment]
@jdknox I have to admit, I'm not really sure what that comment was referring to exactly...

**Comment by jdknox** [comment]
@bsavery I'm working through those changes now.  I'll let you know if I can figure out the `PyModuleDef` part.

**Comment by bsavery** [comment]
Hey @jdknox any progress?  I have some time off here post siggraph and wanted to ramp up getting this going.  We need a python3 dll of USD to make a blender plugin, and that's my first goal here.

Unless George has any recommendations, I'll continue trying to do that.

**Comment by jdknox** [comment]
@bsavery I've only got as far as futurizing the python2 code to python3 compatibility.  It compiles and passes all tests using python2 and Blender's python3.5, but I haven't gotten to the C code yet.

**Comment by darknoon** [comment]
@bsavery @enzyme69 I was getting a little impatient waiting for all of these build shenanigans to give us USD on Python 3, so I started building a blender export plugin that just uses a subprocess to pass data across to Python 2.7.

If anyone is interested in combining efforts, that would be great! Right now it can only export meshes + object locations.
https://github.com/darknoon/BlenderUSDZ

**Comment by meshula** [comment]
Now that USD can be built without python, and in a monolithic static version, a C++ blender python might be another path forward.

@darknoon That's an interesting approach (shenanigans on shenanigans!)

**Comment by meshula** [comment]
There's now work on the blender site itself to integrate USD directly into Python, and nVidia has posted a patch that allows Python3 USD bindings. Closing this issue in deference to those two efforts.
