### ISSUE TITLE
configure.cmd is not found.

### ISSUE THREAD

**Issue by kihoku** [vfxpro99/usd-build-club#14]
Building USD on Windows
https://github.com/vfxpro99/usd-build-club/wiki/USD-on-Windows

The correct one is not ”.\usd-build-club\configure.cmd” but ”.\usd-build-club\configure-windows.cmd”, I(we) suppose. Would you please re-confirm it?

**Comment by vfxpro99** [comment]
Thanks for the report. fixed!
