### ISSUE TITLE
alebmic<-hdf5 with vs2015 compile

### ISSUE THREAD

**Issue by kSpacer201** [vfxpro99/usd-build-club#16]
I had compiled for many times and found  that  the hdf5 seemed cannot to skip. It seems that the usd needs this part . 
Then i searched on google and found some links .

- [vtk hdf5 : Width with ** ](http://vtk.1045678.n5.nabble.com/vtk-6-2-0-CMake-3-3-0-crash-report-td5733396.html)

and  it gave some modification with two file:
1. [hdf5: fix long long format detection](https://gitlab.kitware.com/ben.boeckel/vtk/commit/a4cf06de481eb2a354d10e7874928200be65c400)
2. [hdf5: detect %I64d specifier](https://gitlab.kitware.com/ben.boeckel/vtk/commit/718941125d967015e366172dd09793268f4c9eb5)

I modified the two files ,and the hdf5 compiled without error. But when I compiled the Alembic part,
It reported:
.....
*** error LNK2019: unresolved external symbol __imp_H5Pset_chunk ****
 .....
Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_HL_LIBRARIES HL)

Then I modified the prerequistites-vc140-x64\alembic.cmd , added;
  
  -HDF5_ROOT=path 

But it didn`t work. - ,- .

**Comment by kSpacer201** [comment]
I changed the cmake to 3.2.2 , ok. T.T

**Comment by vfxpro99** [comment]
I am stuck on HDF5 as well. Are you saying that upgrading cmake to 3.2.2 solves the HDF5 build failures? Or did you need to patch the two files AND upgrade cmake to 3.2.2? I'm on cmake 3.4, so I'm guessing the patches to hdf5 are also necessary.

**Comment by kSpacer201** [comment]
Yeah , it seemed like that the HDF5 parts can work after modified the two files (no interrupt dialogs). But then the alembic part got errors. T _ T ,then I modified some cmake files to skip the HDF5 parts (the  finding-HDF5 part was contained in the cmake and some version cmake could't find HDF5 when another could.) . Then , excellent ,I got the working USD without abc !  So confused about the almebic with  HDF5. I want to try to make the HDF5 to work and spend some time to record the progress of my building .

**Comment by meshula** [comment]
I see that the new Pixar build scripts address building Alembic with HDF5. I think the scripts here can be updated to do what they do. Search for HDF5 here:

https://github.com/PixarAnimationStudios/USD/blob/dev/build_scripts/build_usd.py

Created a new issue to open a discussion about the new build scripts and how build club relates:

https://github.com/vfxpro99/usd-build-club/issues/19

**Comment by kSpacer201** [comment]
Thank you so much. I will try this script. ^_^
