### ISSUE TITLE
usd for maya on mac crash on export

### ISSUE THREAD

**Issue by michaellevin** [vfxpro99/usd-build-club#18]
Hi there, I've successfully built usd0maya plugin, it loads in maya but unfortunately crashes when export. 

I've changed build-macos-maya.sh a little, here are the env variables:

`cmake ${SOURCEDIR} \
  -DCMAKE_INSTALL_PREFIX="${BUILDDIR}" \
  -DCMAKE_PREFIX_PATH="${BUILDDIR}" \
  -DPXR_INSTALL_LOCATION="$HOME/Library/Pixar/USD_maya/local/third_party/maya/plugin/" \
  -DPXR_BUILD_MAYA_PLUGIN=1 \
  -DPXR_BUILD_IMAGING=1 -DPXR_BUILD_USD_IMAGING=1 \
  -DPXR_BUILD_ALEMBIC_PLUGIN=0 \
  -DMAYA_LOCATION=/Applications/Autodesk/maya2017 \
  -DTBB_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libtbb.dylib \
  -DTBB_LIBRARIES=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS \
  -DMAYA_OpenMayaAnim_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libOpenMayaAnim.dylib \
  -DMAYA_OpenMayaRender_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libOpenMayaRender.dylib \
  -DMAYA_OpenMayaUI_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libOpenMayaUI.dylib \
  -DMAYA_OpenMaya_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libOpenMaya.dylib \
  -DMAYA_Foundation_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libFoundation.dylib \
  -DMAYA_OpenMayaFX_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libOpenMayaFX.dylib \
  -DMAYA_tbb_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libtbb.dylib \
  -DPXR_tbb_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libtbb.dylib \
  -DTBB_ROOT_DIR=/Applications/Autodesk/maya2017/include \
  -DPXR_MALLOC_LIBRARY:path=/Applications/Autodesk/maya2017/Maya.app/Contents/MacOS/libtbbmalloc.dylib \
  -DPYTHON_EXECUTABLE=/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/2.7/bin/python2.7 \
  -DPYTHON_INCLUDE_DIR=/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/2.7/include/python2.7 \
  -DPYTHON_LIBRARY=/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib \
  -DPYTHON_LIBRARIES=/Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib \
  -DPYSIDE_BIN_DIR="/Applications/Autodesk/maya2017/Maya.app/Contents/bin" \
  -DALEMBIC_DIR="${BUILDDIR}" \
  -DDOUBLE_CONVERSION_DIR="${BUILDDIR}" \
  -DGLEW_LOCATION="${BUILDDIR}" \
  -DOIIO_LOCATION="${BUILDDIR}" \
  -DOPENEXR_ROOT_DIR="${BUILDDIR}" \
  -DOPENSUBDIV_ROOT_DIR="${BUILDDIR}" \
  -DQT_ROOT_DIR="${BUILDDIR}" \
  -DPTEX_LOCATION="${BUILDDIR}" \
  -DOpenMP_CXX_FLAGS=-std=c++11 \
  -DOpenMP_C_FLAGS=-std=c++11 \
  -DBoost_INCLUDE_DIR="${BUILDDIR}/include" -DBoost_LIBRARY_DIR="${BUILDDIR}/lib" \
  -G Xcode
`
There were a couple errors I mentioned  during building is the following

1) Couldn't find TBB ... 
2) cp: local/third_party/maya/plugin/pxrUsd.dylib: No such file or directory

But everything seems ok in /tmp/maya-usd. So I copied everything to Library/Pixar and plugin loaded. But when it crashes with the following log (look .crash.txt file):

Any ideas where to look ?
[Maya_2017-06-06-194023_MP1.crash.txt](https://github.com/vfxpro99/usd-build-club/files/1057947/Maya_2017-06-06-194023_MP1.crash.txt)

**Comment by vfxpro99** [comment]
Is it possible that the Maya SDK is not installed at /Applications/Autodesk/maya2017/include ?

You should be able to see /Applications/Autodesk/maya2017/include/tbb and /Applications/Autodesk/maya2017/include/serial in that directory.

**Comment by michaellevin** [comment]
Thank you for the reply,

Yes, of course -- there are these folders in the include directory. I think it would've not been built otherwise.

**Comment by michaellevin** [comment]
I try to rebuild all,
'couldn't find tbb' - fixed, but the other error is

`CMake Error in third_party/maya/lib/px_vp20/CMakeLists.txt:
  Target "px_vp20" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Applications/Autodesk/maya2017/usd-build/USD/../../devkit/plug-ins"

  which is prefixed in the source directory.


CMake Error in third_party/maya/lib/pxrUsdMayaGL/CMakeLists.txt:
  Target "pxrUsdMayaGL" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Applications/Autodesk/maya2017/usd-build/USD/../../devkit/plug-ins"

  which is prefixed in the source directory.


CMake Error in third_party/maya/lib/usdMaya/CMakeLists.txt:
  Target "usdMaya" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Applications/Autodesk/maya2017/usd-build/USD/../../devkit/plug-ins"

  which is prefixed in the source directory.


CMake Error in third_party/maya/lib/usdMaya/CMakeLists.txt:
  Target "_usdMaya" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Applications/Autodesk/maya2017/usd-build/USD/../../devkit/plug-ins"

  which is prefixed in the source directory.


CMake Error in third_party/maya/plugin/pxrUsd/CMakeLists.txt:
  Target "pxrUsd" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/Applications/Autodesk/maya2017/usd-build/USD/../../devkit/plug-ins"

  which is prefixed in the source directory.`

last time I managed it somehow, but this time I can't find the solution

**Comment by meshula** [comment]
Looking at the error message, it seems that you are bumping into this -

https://stackoverflow.com/questions/25676277/cmake-target-include-directories-prints-an-error-when-i-try-to-add-the-source

**Comment by michaellevin** [comment]
thank you, I think I've managed the compilation. The first issue was that some library paths were mixed and it took the wrong library.
