### ISSUE TITLE
Differentiate official build script from build club

### ISSUE THREAD

**Issue by meshula** [vfxpro99/usd-build-club#19]
Pixar has released a new build script here -

https://github.com/PixarAnimationStudios/USD/blob/dev/build_scripts/build_usd.py

It differs from build club in that for the most part it downloads prebuilt binaries of things like HDF5 rather than building them from scratch.

In order that build club continue to be useful, it would be good to list up how the build scripts differ, why you'd choose on or the other, and also harmonize build club to the official build script so that compatible installations result.

**Comment by CreateTheImaginable** [comment]
Building USD and also the USD Maya plugin is tricky enough that will it will be very helpful to compare success or failure results of the two builds!   Maybe one can help the other and vice versa!  

For MacOS 10.12.5 using Xcode 8.3.3:

I tried the new build_usd.py script and it built everything but the usdview executable for me...   I wonder if this is related to either how PySide or Qt4 is installed? Seems like Qt4 is packaged now as a dependancy so we don't have to worry about it.  I installed Pyside using https://www.macports.org as the script recommended ( port install py27-pyside-tools ).  See below.

Has anyone else gotten the new script to build usdview?  

git clone https://github.com/PixarAnimationStudios/USD
cd USD
git checkout dev
cd ..
python USD/build_scripts/build_usd.py -v $HOME/Projects/Pixar/BUILD/USD



For the Maya plugin I used the options below but the plugin crashes Maya when I try to load the plugin...   Also it seems we have to package up the plugin ourselves which can be error prone...

python USD/build_scripts/build_usd.py -v --maya  $HOME/Projects/Pixar/BUILD/USD

Anyone else have better success with the new script and the Maya plugin?

**Comment by meshula** [comment]
I haven't tried the new script yet. I am curious what Maya crash you are seeing. Are you able to get a call stack? I've been launching Maya via lldb in order to get the USD call stack at crash time...

**Comment by CreateTheImaginable** [comment]
I can give it a whirl....    Are you doing anything special to run Maya via lldb?  What lldb set up are you using?    I am getting crashes with the Maya plugin with both builds.   Recently with the usd-build-club build Maya is crashing when I try to export a mesh, even a simple cube...

**Comment by meshula** [comment]
What I do - cd into /Applications/Autodesk/Maya/MacOS/Contents (or wherever the maya app actually hides, I'm on a PC here). Then, lldb maya. r to run, and it should start. If it crashes lldb will give a stack. lldb is the stock one Xcode installs in the path.

**Comment by meshula** [comment]
If the Maya build is still crashing let's open a new issue to track it specifically
