### ISSUE TITLE
VS 2017 Windows build fails due to bad version check in glew dependency command file.

### ISSUE THREAD

**Issue by GiantCowFilms** [vfxpro99/usd-build-club#20]
The VS 2017 cmd file for glew has a check to ensure it is using VS 2015. This causes the prerequisistes setup to fail.

```batch
REM ensure a 64 bit development environment using VS2015
IF NOT %VisualStudioVersion%=="14.0" ^
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
```

**Comment by meshula** [comment]
Thanks for the note. There were a few instances of that bug. Here's the fix:

https://github.com/vfxpro99/usd-build-club/commit/0d6cd78da2904a2afa268077616d3ffc8fb0ed1c
