### ISSUE TITLE
Building with alternative CMake generators? (NMake Makefiles JOM)

### ISSUE THREAD

**Issue by boberfly** [vfxpro99/usd-build-club#23]
Hi all,

Has anyone tried to build USD using NMake (JOM)? It's the NMake replacement which can do multicore builds. https://wiki.qt.io/Jom

So far I've tried it and it gets stuck with:
`pxr\base\lib\arch\CMakeFiles\arch.dir\flags.make(5) : fatal error U1033: syntax error : '/Zc' unexpected`

I'll keep digging, perhaps here:
https://github.com/PixarAnimationStudios/USD/blob/master/cmake/defaults/msvcdefaults.cmake#L29

The colon is getting dropped somehow.

Why I want this alternative way of building is that I'm currently 'experimenting' with a docker container which doesn't have MSTarget available.

Cheers!

**Comment by boberfly** [comment]
Aha it's all that whitespace that trips it up, removing it seems to make it build now, great!
https://github.com/PixarAnimationStudios/USD/pull/512

**Comment by meshula** [comment]
Interesting issue, good detective work!
