### ISSUE TITLE
Bug: hard coded assumption about VS version, and existence of Powershell.

### ISSUE THREAD

**Issue by enzyme69** [vfxpro99/usd-build-club#25]
I am following every step here:
https://github.com/vfxpro99/usd-build-club/wiki/USD-on-Windows

But I have issue with not able to install Microsoft Visual Studio whichever version.

![prtscr capture_2](https://user-images.githubusercontent.com/3952687/44567169-8610cd00-a7b4-11e8-9102-37b0a853470c.png)

Even after installing Community Version of MVS 15, I don't seem to manage to make this work.

**Comment by enzyme69** [comment]
Seems like I manage to get VS2015, and when running prerequisite:

![prtscr capture_3](https://user-images.githubusercontent.com/3952687/44569619-5c5ca380-a7be-11e8-986d-6eb0d631876a.png)

**Comment by meshula** [comment]
Thanks for the feedback. It looks like we need to update the script to not be hard coded to visual studio version. Also, the script assumes you have PowerShell installed. That needs to be corrected, or documented.

I changed the title to show that point.

**Comment by meshula** [comment]
I tested the VS2017 version of the script which worked for me. I updated the script to make it match the Wiki page, and corrected a typo on the Wiki page. If you could install VS2017, and Powershell, git pull the build club repo to get the fixed script, then check the instructions under on the Wiki under "build club method" perhaps you'll have better luck.

**Comment by meshula** [comment]
If this issue comes up again, please feel free to reopen this issue.
