### ISSUE TITLE
MacOS Brew script: Complaining about boost_python missing.

### ISSUE THREAD

**Issue by melMass** [vfxpro99/usd-build-club#26]
Hi,

First of thanks for those amazing repos. Making better build scripts together is a really neat idea.

I did not knew that you could use brew to create isolated environments. It's pretty effective and powerful.

There seems to be an issue with boost_python. It does install well in the stage's brew folder but is not picked up by USD's Cmake.

```log
 Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path:
  /USD_Explorations/usdview-native/deps/src/USD-18.09/stage/homebrew/include


  Could not find the following Boost libraries:

          boost_python
```

I have tried setting envs like so:
```shell
BOOST_LIBRARYDIR=/Volumes/4TB/PROJETS/FX/USD_Exploration/usdview-native/deps/src/USD-18.09/stage/homebrew/Cellar/boost-python/1.67.0/lib
```

But I'm still getting the same issue.
Except from that all deps seems to build well.

**Comment by meshula** [comment]
Thanks for the report. The official cmake script to find Boost is very fussy. There might be further steps necessary to teach cmake where the  boost python library is. If you look at the CMakeCache.txt file, where did it find the other boost libraries? From your homebrew directory, or some other place?

**Comment by meshula** [comment]
It seems others have had success. If this issue persists, please reopen.

**Comment by melMass** [comment]
I haven't tried in a long time, but perfect timing as I'm actually back at it!
Thanks
