### ISSUE TITLE
Error while executing build-prerequisites-vs2017.cmd on windows

### ISSUE THREAD

**Issue by tusharsankhala** [vfxpro99/usd-build-club#27]
Hi All,

This is the error i am getting OpenEXR is no found, and error while build alembic:

-- Project build dir   = F:/GitHub_Repos/stage/prereq/build/oiio
-- Project install dir = F:/GitHub_Repos/stage/local
-- platform = windows
-- CMAKE_CXX_COMPILER is C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe
-- CMAKE_CXX_COMPILER_ID is MSVC
-- Setting Namespace to: OpenImageIO_v1_8
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  **Could NOT find OpenEXR: Found unsuitable version "1.6.1", but required is
  at least "2.0" (found ILMBASE_INCLUDE_PATH-NOTFOUND)**
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  src/cmake/modules/FindOpenEXR.cmake:149 (find_package_handle_standard_args)
  src/cmake/externalpackages.cmake:62 (find_package)
  CMakeLists.txt:118 (include)

-- Configuring incomplete, errors occurred!
See also "F:/GitHub_Repos/stage/prereq/build/oiio/CMakeFiles/CMakeOutput.log".
See also "F:/GitHub_Repos/stage/prereq/build/oiio/CMakeFiles/CMakeError.log".
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: install.vcxproj
Building Alembic
"Retrieving Alembic at version 1.6.1 for compatibility"
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at a3aa7585 Bumping to 1.6.1
-- CMAKE SYSTEM NAME: Windows
-- The install dir is F:/GitHub_Repos/stage/local
CMake Error at cmake/Modules/FindIlmBase.cmake:157 (MESSAGE):
  ilmbase libraries (Half, Iex, IlmThread, Imath) not found, required
Call Stack (most recent call first):
  cmake/AlembicIlmBase.cmake:36 (FIND_PACKAGE)
  CMakeLists.txt:217 (INCLUDE)

**-- Configuring incomplete, errors occurred!**
See also "F:/GitHub_Repos/stage/prereq/build/alembic/CMakeFiles/CMakeOutput.log".
See also "F:/GitHub_Repos/stage/prereq/build/alembic/CMakeFiles/CMakeError.log".
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

**MSBUILD : error MSB1009: Project file does not exist.**
Switch: install.vcxproj

Could anyone help.
 
Thanks,
Tushar

**Comment by meshula** [comment]
Thanks for the report. I suspect the scripts need to be updated to reflect recent changes in the OpenEXR repo.

**Comment by meshula** [comment]
Pushed corrected openexr build scripts. Please LMK if that resolves building OpenEXR.

**Comment by tusharsankhala** [comment]
Thanks, 
Your fix worked there is one more i am getting regarding **GLEW linker error**:

arrayTexture.obj : error LNK2001: unresolved external symbol __imp___glewTexImage3D
14>ptexTexture.obj : error LNK2001: unresolved external symbol __imp___glewTexImage3D
14>simpleShadowArray.obj : error LNK2001: unresolved external symbol __imp___glewTexImage3D
14>arrayTexture.obj : error LNK2001: unresolved external symbol __imp___glewTexSubImage3D
14>baseTexture.obj : error LNK2001: unresolved external symbol __imp___glewCompressedTexImage2D
14>bindingMap.obj : error LNK2001: unresolved external symbol __imp___glewGetActiveAttrib
14>bindingMap.obj : error LNK2001: unresolved external symbol __imp___glewGetActiveUniform
14>bindingMap.obj : error LNK2001: unresolved external symbol __imp___glewGetAttribLocation
14>bindingMap.obj : error LNK2001: unresolved external symbol __imp___glewGetProgramiv
14>bindingMap.obj : error LNK2001: unresolved external symbol __imp___glewGetUniformLocation
14>bindingMap.obj : error LNK2001: unresolved external symbol __imp___glewProgramUniform1i
14>bindingMap.obj : error LNK2001: unresolved external symbol __imp___glewGetActiveUniformBlockName
14>bindingMap.obj : error LNK2001: unresolved external symbol __imp___glewGetUniformBlockIndex
14>bindingMap.obj : error LNK2001: unresolved external symbol __imp___glewUniformBlockBindi

Would be great if you could help.

Thanks in Advance.

**Comment by meshula** [comment]
Did CMake find the glew built by the script, or did it find another glew elsewhere in your system? If you check the CMakeCache.txt file, you should be able to see the path there.

**Comment by meshula** [comment]
Windows builds appear to be working. If this issue persists, please reopen.
