### ISSUE TITLE
No luck with macOs 10.13 and Xcode 10

### ISSUE THREAD

**Issue by MarjanPl** [vfxpro99/usd-build-club#28]
Hi, 
let me first say that i have not to much of an idea about this topic. I was just following the instructions.

Most of the build process seems to work just fine, except at the end i get this from the terminal:

```
ooking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found PythonInterp: /Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/2.7/bin/python2.7 (found suitable version "2.7.10", minimum required is "2.7") 
-- Found PythonLibs: /Applications/Autodesk/maya2017/Maya.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (found suitable version "2.7.11", minimum required is "2.7") 
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   python
--   system
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jinja2
-- Found TBB: /Applications/Autodesk/maya2017/include/include (found version "4.4") found components:  tbb 
CMake Error at /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenEXR (missing: OPENEXR_LIBRARIES)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindOpenEXR.cmake:92 (find_package_handle_standard_args)
  cmake/defaults/Packages.cmake:104 (find_package)
  CMakeLists.txt:34 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/ploederlm/Documents/USD_maya/USD_maya/CMakeFiles/CMakeOutput.log".
-------------------------------------------------
4/5 Building and installing the Maya plugin
-------------------------------------------------
xcodebuild: error: 'usd.xcodeproj' does not exist.
Failed to build for Maya, exiting

```

The first issue was that the build process includes libGLEW.2.0.0.dylib. However, libGLEW.2.1.0.dylib was downloaded. I got around this by changing the names in 3 files of use-build-club (build-macos-maya.sh, glee.sh). this got me further but...

As you can see it complains about a missing jinja2 module (which in installed via pip install Jinja2). Unfortunately this didn´t do the trick.

Also, nothing is ever been written to /tmp.

Any Idea?

**Comment by meshula** [comment]
Thanks for the report, it seems the OpenEXR script needs updating, in addition to the GLEW script.

**Comment by PremiumArts** [comment]
Here we have the same problem with the macos-maya build.
What is the newest status of this issue?
Thank you.

**Comment by meshula** [comment]
The fix to the OpenEXR script for Windows worked, so the same should be applied for mac. (https://github.com/vfxpro99/usd-build-club/issues/27)

**Comment by meshula** [comment]
This patch addresses the OpenEXR issue.

https://github.com/vfxpro99/usd-build-club/commit/85f15e40af6f25e191620095709938ba80860fc1

Instructions also updated to reflect installing PySide2. Please open a new comment if further issues are encountered.
