### ISSUE TITLE
Windows: recommend installing Jinja2?

### ISSUE THREAD

**Issue by rhaleblian** [vfxpro99/usd-build-club#31]
With Jinja2, you're more likely to get `bin/usdGenSchema`. An out-of-the-box build of maya-usd (Autodesk's take on the AL and Pixar Maya plugins) expects it.

    pip install jinja2

Later on guys. And thanks for putting this repo together, i'm building on all 3 plaftorms and it's super helpful.

**Comment by meshula** [comment]
Thanks for the note, all the instructions updated to mention installing jinja2!

**Comment by rhaleblian** [comment]
Hi Nick! Cool.
