### ISSUE TITLE
OSX Build Error

### ISSUE THREAD

**Issue by skarone** [vfxpro99/usd-build-club#4]
The following build commands failed:
    CompileC /Users/ignacio/workspace/Projects/stage/pxr/imaging/lib/glf/usd.build/Release/glf.build/Objects-normal/x86_64/baseTexture.o pxr/imaging/lib/glf/baseTexture.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by vfxpro99** [comment]
Two questions, which version of clang (or Xcode) are you using? And could you post the baseTexture error message?

**Comment by vfxpro99** [comment]
There is new code available. Please pull latest USD from pixar and build club from here, checkout the dev branch of USD, and go through the build club steps again. If the problem persists, feel free to re-open an issue.
