### ISSUE TITLE
Building OpenEXR

### ISSUE THREAD

**Issue by kretash** [vfxpro99/usd-build-club#5]
When building OpenEXR I had to first build Zlib and then add  -DZLIB_ROOT="C:/zlib" to the second project in order for it to build successfully. 

Not a big problem, but though I comment on it just in case anybody else has the same issue.

**Comment by vfxpro99** [comment]
When you say the second project, do you mean openexr.cmd needs to be amended to refer to zlib?

**Comment by kretash** [comment]
Yes, cmake could not build without the reference.

`cmake -G "Visual Studio 14 2015 Win64" -DILMBASE_PACKAGE_PREFIX="%current%\local"  -DZLIB_ROOT="C:/zlib" -DCMAKE_INSTALL_PREFIX="%current%\local" ..\..\openexr\OpenEXR`

It also did not work with a prebuilt version of Zlib. It needed the built version. Thankfully you guys have a zlib.cmd that built it and all I had to do is add that DZLIB_ROOT argument.

**Comment by vfxpro99** [comment]
If you are using zlib.cmd, then -DZLIB_ROOT would be %current%\local. Could you try the latest and reopen this issue if the problem persists? 1318dc7c77be10fcec4e046ecb0534c2a2c8a9c6
