### ISSUE TITLE
Alembic should be built to 1.5.2 (per USD reqs) or 1.6.x per VFX platform

### ISSUE THREAD

**Issue by sunyab** [vfxpro99/usd-build-club#6]
The Alembic portion of the build club scripts build from the head of the Alembic github repository. That appears to be in a broken state right now, as I get a number of errors when building Alembic on OSX. 

These scripts should probably be building a stable release of Alembic instead. The USD documentation specifies 1.5.2 as the required version, and the VFX platform (http://www.vfxplatform.com/) states 1.5.8 for CY 2016 and 1.6.x for CY 2017.

**Comment by vfxpro99** [comment]
Fixed as of 419dac49fe404d8a91dae97aa0212aade7b82c7c Please reopen if the build problems persist.
