### ISSUE TITLE
_glf.pyd import freezes Python process

### ISSUE THREAD

**Issue by krzykli** [vfxpro99/usd-build-club#7]
First of all thanks a lot for setting up this repo! It's great!
I've managed to successfully build USD without a single error, but when I try to run usdview the Python process freezes.
I've tracked the issue down to an import of Glf module, after that Python becomes unresponsive.
Do you have any ideas what might be the cause of this?

Thanks!

**Comment by CreateTheImaginable** [comment]
What platform are you running on?   I am seeing  something similar on macOS 10.12.1.   Both usdcat and usdview used to work but now after doing a new compiled build both processes freeze up after running them on the command line.  Note, I compiled the prerequisites and did not use brew for this build.

**Comment by krzykli** [comment]
I'm running on Windows 7 actually, so it seems the issue affects both platforms.

**Comment by vfxpro99** [comment]
Hi I've just confirmed that the deadlock occurs on Windows 10 as well.

**Comment by krzykli** [comment]
Cool, when was the last time you have successfully ran usdview on Win/MacOs @vfxpro99 ? Was it before or after [Bringing dev_win_ip up to date with dev](https://github.com/PixarAnimationStudios/USD/pull/100) ?

**Comment by vfxpro99** [comment]
I haven't tried syncing before that yet. The general consensus at the moment seems to be that one of the dependencies might be causing the issue, as others who build the prerequisites several weeks ago, but are at the head revision of USD are functional at the moment.

**Comment by krzykli** [comment]
Ok, the latest merge commit in the `dev_win_ip ` branch is massive, so it looked a bit scary to me, but if you're saying other people got it working with the head revision then indeed it seems like a third party issue.

**Comment by meshula** [comment]
I reported this over in the USD issues: It's OpenImageIO deadlocking.

[External Code]	
OpenImageIO.dll!00007ffbfee33660()	Unknown
OpenImageIO.dll!00007ffbfee34e99()	Unknown
OpenImageIO.dll!00007ffbfee34c88()	Unknown
OpenImageIO.dll!00007ffbfee33e57()	Unknown
OpenImageIO.dll!00007ffbfee33eb6()	Unknown
OpenImageIO.dll!00007ffbfee34869()	Unknown
OpenImageIO.dll!00007ffbfe7c2339()	Unknown
[External Code]	
OpenImageIO.dll!00007ffbfee74ba7()	Unknown
OpenImageIO.dll!00007ffbfee74cf9()	Unknown
[External Code]	
python27.dll!000000001e125268()	Unknown

**Comment by vfxpro99** [comment]
Regressed and found a commit prior to the deadlock issue. Please pull and build OIIO again.

**Comment by lgritz** [comment]
Can anybody (on either platform) catch this with a debug build of OpenImageIO and send me the stack traces that reveal exactly where in OIIO the threads are stuck?

**Comment by meshula** [comment]
please see https://github.com/OpenImageIO/oiio/issues/1572#issuecomment-263493108
