### ISSUE TITLE
usdcat and usdview used to work but both processes freeze up after running on command line.

### ISSUE THREAD

**Issue by CreateTheImaginable** [vfxpro99/usd-build-club#8]
This may be related to the "_glf.pyd import freezes Python process" issue.    Both usdcat and usdview used to work but now after doing a new compiled build both processes freeze up after running them on the command line.  Note, I compiled the prerequisites and did not use brew for this build.

To get usdview to compile on MacOS 10.12.1 you need to un-comment lines 135 and 138 in the build_prerequisites.sh file so that qt_4_8_7.sh and pyside.sh run.  Both take a while but will compile, you will be asked for the admin password when needed, about 4 times.

Both usdcat and usdview used to work but something must have recently changed because they now freeze on the command line after setting the correct PYTHONPATH.

```
export PYTHONPATH=$PYTHONPATH:~/Library/Pixar/stage/local/lib/python
export PATH=$PATH:~/Library/Pixar/stage/local/bin
```

**One thing to note is that if you run them without parameters they do not freeze but print to standard output as expected...**

>usdcat
usage: usdcat [-h] [-o file] [--usdFormat usda|usdb|usdc] [-f]
              inputFiles [inputFiles ...]
usdcat: error: too few arguments

>usdview
usage: usdview
       [-h] [--renderer {opt,simple}] [--select PRIMPATH] [--clearsettings]
       [--norender] [--unloaded] [--timing]
       [--memstats {none,stage,stageAndImaging}] [--numThreads NUMTHREADS]
       [--ff FIRSTFRAME] [--lf LASTFRAME] [--complexity COMPLEXITY]
       [--quitAfterStartup]
       usdFile
usdview: error: too few arguments

**Comment by vfxpro99** [comment]
Found a commit in OIIO that does not deadlock. Please pull and rebuild OIIO.

**Comment by CreateTheImaginable** [comment]
When using the Building USD on macOS - Experimental method on macOS 10.12.1 

```
  git clone https://github.com/vfxpro99/usd-build-club.git
  mkdir stage
  cd stage
  ../usd-build-club/build-macos.sh
```

I am still getting the deadlock error.

**Comment by vfxpro99** [comment]
In your stage directory, please build as debug,

````
cmake --build . --target install --config Debug
````

Then you should be able to attach a debugger and get a call stack. If you could post that in this thread, it would help track down the issue. Local builds aren't showing the issue here unfortunately.

Update, tried on two other machines without trouble....

**Comment by CreateTheImaginable** [comment]
This might be it? I haven't tried with the debugger yet but I am getting a **"No rule to make target install"** in build/oiio

When I run the ./OpenImageIO.sh script in prerequisites-macOS it breaks on line 49 - "cmake --build . --target install --config Release"

> ./OpenImageIO.sh
> make: *** No rule to make target `install'.  Stop.

**Comment by vfxpro99** [comment]
That error means that the makefile was not properly created.

Does the directory /path/to/your/stage/prereq/build/oiio exist?
Also does /path/to/your/stage/prereq/oiio exist?
