### ISSUE TITLE
Viewport in usdview does not display geometry

### ISSUE THREAD

**Issue by krzykli** [vfxpro99/usd-build-club#9]
I've rebuilt USD on Win 7 and #7 is gone. Good stuff!
Unfortunately, the viewport in usdview doesn't render anything. Here's what I get in the console:
```
λ usdview HelloWorld.usda
Could not parse application stylesheet
Warning: in HdGLSLProgram::Link at line 172 of O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\USD\pxr\imaging\lib\hd\glslProgram.cpp -- Failed to link shader:
Vertex info
-----------
0(132) : warning C7050: "_dc.instanceCoords[0]" might be used before being initialized
0(132) : warning C7050: "_dc.instanceCoords[0]" might be used before being initialized

Geometry info
-------------
(0) : error C5133: multiple outputs associated with semantic "SBO_BUFFER[0]"
(0) : error C5133: multiple outputs associated with semantic "SBO_BUFFER[0]"
(0) : error C5133: multiple outputs associated with semantic "SBO_BUFFER[0]"

Traceback (most recent call last):
  File "O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\stage\local\lib\python\pxr\Usdviewq\stageView.py", line 1744, in paintGL
    self.drawSelHighlights)
  File "O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\stage\local\lib\python\pxr\Usdviewq\stageView.py", line 1473, in renderSinglePass
    self._renderer.Render(pseudoRoot, self._renderParams)
pxr.Tf.ErrorException:
        Error in 'Hd_DrawBatch::_GetDrawingProgram' at line 239 in file O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\USD\pxr\imaging\lib\hd\drawBatch.cpp : 'Failed verification: ' res ''
        Error in 'Hd_IndirectDrawBatch::ExecuteDraw' at line 986 in file O:\dev\krzysztof.klimczyk\workspace\usdBuildFixed\Projects\USD\pxr\imaging\lib\hd\indirectDrawBatch.cpp : 'Failed verification: ' glslProgram ''
```
Is this happening to anyone else?

[ Edit ] If I disable /hello/world location the viewport seems to work just fine.

Thanks,
kk

**Comment by krzykli** [comment]
Plus the alternate background color in the tree widget looks slightly off. In the log above you can see
`Could not parse application stylesheet` but when loading the same qss file in Qt Designer everything looks correct, or at least it seems so.

![screengrab](https://cloud.githubusercontent.com/assets/6304331/20734728/8462eafe-b6ef-11e6-9f12-38829ab90fed.png)

**Comment by vfxpro99** [comment]
Does the fix in your repo resolve the issue? https://github.com/krzykli/USD/commit/980e5b58be7a80333b63ce643e772b8b4cd30345

**Comment by krzykli** [comment]
Yes, I looked into this and fixed it locally. I'll submit a pull request shortly.
Of course this just fixes the style sheet issue.

Edit:
https://github.com/PixarAnimationStudios/USD/pull/113

![afterfix](https://cloud.githubusercontent.com/assets/6304331/20738846/63091b56-b70a-11e6-8897-2d4483819c14.png)

**Comment by vfxpro99** [comment]
It's working on Windows 10. Is it possible that your GL driver does not support a recent enough version for Hydra? Hydra needs GL4.3+. Can you try running usdview with the simple render command line option? That should make it run without GL4 features.

**Comment by krzykli** [comment]
Thanks for confirming that @vfxpro99.
I have GL4.3 and the viewport was drawn correctly only when I deactivated the primitive (so I could see the bounding box). Anyway, updating Nvidia drivers did the trick for me so if anyone else hits this you might want to do the same :)
Closing.

**Comment by vfxpro99** [comment]
Great news :)
